= Contributing to this document

https://www.gbif.org[GBIF] invites community members to contribute to our [digital documentation system](). 

If you are a first-time user, please don't let the code-developer vernacular of 'branches', 'pull requests' and 'commits' frighten you off. Our use of GitHub, while squarely based on its technical capabilities, is equally important from an editorial perspective. The design and format of the materials we publish through this system aims to ensure that any guidance we prepare and commission is uniform, reliable, reusable, versioned, and up-to-date. Your contributions are vital to achieving this. 

We code documents in this system using a lightweight code called https://asciidoctor.org/docs/user-manual/[AsciiDoc] (see some https://github.com/gbif/doc-documentation-guidelines/blob/1.0/index.en.adoc#guidelines-for-document-authors[key tips here]). We apply United Nations editorial conventions (tl;dr: British English with -ize endings) with regard to http://dd.dgacm.org/editorialmanual/ed-guidelines/style/spelling.htm/[spelling] and http://dd.dgacm.org/editorialmanual/[style].

== What are we looking for?

=== Community review

By maintaining each document’s source text in a public GitHub repository, or "repo", community members have ready access to this material. Each time a new draft document is completed, we will ask members of relevant GBIF communities of practice (the intended users and beneficiaries of these documents) to offer direct input and feedback. The effect of this process is two-fold: to ensure the quality of the documentation and to foster community discussion and collaboration. https://github.com/gbif/doc-documentation-guidelines/blob/1.0/index.en.adoc#community-peer-review-process[Read more about the community review process].

=== Content issues

We encourage reviewers and users to help improve this document by offering comments, suggestions and corrections at any stage in its life cycle. In short: **if you see something, say something**.

Improvements can take any number of forms, but your suggestions should aim to:

* make the document more coherent, consistent, or readable
* add missing information
* correct factual errors
* fix typos 
* bring it up-to-date

In general, we ask that you create an issue when for your suggestions and corrections.

video::430632177[vimeo]

You can also use issues to highlight more technical, less editorial matters, such as errors and bug reports, recommendations on usability and formatting or suggestions on additional topics for us to consider covering in our documentation.

Be sure that you are logged in to your GitHub account if you have one—and if you don't have one, please consider https://github.com/join[creating one]. By doing so, you can ensure transparency and openness in the community peer-review process, enable authors to ask you about or clarify the issues you raise, track the progress of your suggestions and make certain that GBIF can properly credit your contributions.

video::430640810[vimeo]

=== Translations

GBIF.org is currently available in ten languages (https://www.gbif.org/[English], https://www.gbif.org/ar/[Arabic], https://www.gbif.org/zh/[Simplified Chinese], https://www.gbif.org/fr/[French], https://www.gbif.org/ru/[Russian], https://www.gbif.org/es/[Spanish], https://www.gbif.org/zh-tw[Traditional Chinese], https://www.gbif.org/ja/[Japanese], https://www.gbif.org/pt/[Portuguese] and https://www.gbif.org/uk/[Ukrainian]), so we will be more than happy to support efforts to build on the achievements of https://www.gbif.org/translators/[our volunteer translators] by translating GBIF's digital documentation. 

We are grateful for the generous support we receive from https://crowdin.com/[CrowdIn]. You can see all the translation projects we manage https://crowdin.com/profile/timrobertson100[here].

Existing non-English documents and translations

* OpenRefine
* Guide to effective node management

== What are we *not* looking for?

We use GitHub to manage and maintain the source material of our documentation because it is findable and accessible  . We always welcome suggestions  

* Code and code review
* Technical set-up and configuration
* Security issues

== How to contribute

0. https://www.vimeo.com/430640810[Create a GitHub account].
1. Read the documents
2. See something? Say something by https://vimeo.com/430632177[creating an issue]
3. Follow and support the conversation

=== Credit

a

=== Licensing

a

=== Code of conduct

All interactions must comply with the https://www.gbif.org/code-of-conduct[Code of Conduct for GBIF activities].
