https://docs.gbif.org/documentation-guidelines/[image:https://docs.gbif.org/documentation-guidelines/gbif-document-shield.svg[GBIF Document]]
https://doi.org/10.35035/doc-vf1a-nr22[image:https://zenodo.org/badge/DOI/10.35035/doc-vf1a-nr22.svg[doi:10.35035/doc-vf1a-nr22]]
https://creativecommons.org/licenses/by-sa/4.0/[image:https://img.shields.io/badge/License-CC%20BY%2D-SA%204.0-lightgrey.svg[CC BY-SA 4.0]]
https://builds.gbif.org/job/doc-publishing-dna-derived-data/lastBuild/console[image:https://builds.gbif.org/job/doc-publishing-dna-derived-data/badge/icon[Build status]]
https://crowdin.com/project/publishing-ddd/[image:https://badges.crowdin.net/publishing-ddd/localized.svg[Translation progress]]

= Publishing DNA-derived data through biodiversity discovery platforms

_This is information *about* this document's source code.  It is not part of the document._

The document is available as HTML and PDF at https://docs.gbif-uat.org/publishing-dna-derived-data/1.0/en/[Publishing DNA-Derived Data Through Biodiversity Discovery Platforms].

The document is built using AsciiDoc, for guidance on how to make changes or suggestions see the https://docs.gbif.org/documentation-guidelines/[GBIF Documentation Guidelines].

== Diagrams

The diagrams have been created using https://app.diagrams.net/[Diagrams.net].  They are exported as SVG (File → Export As… → SVG), with the "Include a copy of my diagram" option selected.  This allows the SVG file to be opened in Diagrams.net for further modification.

Diagrams with multi-line text are additionally exported as PNG, for use in PDFs.  Multi-line text is not yet supported by the PDF output.

Simple diagrams, where labels are generally on one line, are enabled for translation using Crowdin.  These are in the img/web/ct directory.  More complex diagrams will need to be translated in Diagrams.net, and saved with the appropriate filename into the img/web directory.

This work is licensed under a http://creativecommons.org/licenses/by-sa/4.0/[Creative Commons Attribution-ShareAlike 4.0 International License].
