GBIF Document Template
----------------------

// Please delete this text after cloning the repository for a new document!
This repository can be cloned to create the structure for maintaining up-to-date, community-curated documentation for the GBIF network on GitHub. *This file is REQUIRED.*

All documentation should be written in https://asciidoctor.org/docs/asciidoc-writers-guide/[AsciiDoc], a lightweight plain-text format that supports the structural elements needed for producing technical documentation from the same source content in both digital and print formats (see this https://asciidoctor.org/docs/asciidoc-syntax-quick-reference[helpful quick reference guide for AsciiDoc formatting]).

This `README.adoc` file should not normally be part of the document.  It is shown on the GitHub source code page, and should contain information on how issues and contributions should be handled, and how the code might be used (such as build instructions).
// End of text to delete.
// Then please update "template" to the new repositorie's name, minus the doc- prefix, and remove this line.

_This is information *about* this document's source code.  It is not part of the document._

The document is available in a temporary location as https://labs.gbif.org/documents/template/[HTML] and https://labs.gbif.org/documents/template/index.pdf[PDF].

The build status is https://builds.gbif.org/job/doc-template/[image:https://builds.gbif.org/job/doc-template/badge/icon[Build status]]

The document is built using AsciiDoc, for guidance on how to make changes or suggestions see the https://labs.gbif.org/documents/documentation-guidelines[GBIF Documentation Guidelines].
